config/routes.rb
Rails.application.class.routes.draw do
  resources :static_pages

  match "adhoc/attachments/new" => "static_pages#attach_file", :as => :static_page_attach_file
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base

  has_friendly_id :title, :use_slug => true, :approximate_ascii => true

  belongs_to :version_of, :class_name => "StaticPage::Version"
  belongs_to :parent, :class_name => "StaticPage", :foreign_key => "parent_id"

  has_many :children, :class_name => "StaticPage", :foreign_key => "parent_id", :order => "position"

  validates_presence_of :title, :content
  validates :position, :numericality => { :only_integer => true }

  validate :directory_or_child
  def directory_or_child
    if work_as_directory and parent_id
      self.errors[:base] << I18n.t("activerecord.errors.static_page.directory_or_child")
    end
  end

  scope :without_parent,  where("parent_id IS NULL")
  scope :as_directory,    where(:work_as_directory => true)

  def self.version_of(version)
    if version.kind_of?(String)
      version = StaticPage::Version.find_by_name(version)
    end

    [I18n.locale.to_s, nil].each do |l|
      if p = find_by_version_of_id_and_locale(version.id, l)
        return p
      end
    end
    nil
  end

  before_destroy :check_children_before_destroy
  def check_children_before_destroy
    self.class.where(:parent_id => id).count == 0
  end

  has_text_search :title, :content
end

app/models/static_page/version.rb
class StaticPage::Version < ActiveRecord::Base

  validates :name, :presence => true

  def label
    if name =~ /\Akey:(.*)\Z$/i
      I18n.t "static_pages.versions.#$1.label"
    else
      name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  only_admins :new, :create, :edit, :update, :destroy, :index, :attach_file

  def new
    @static_page = StaticPage.new
  end

  def create
    @static_page = StaticPage.new(params[:static_page])
    if @static_page.save
      flash[:notice] = t("static_pages.create.success")
      redirect_to static_page_path(@static_page)
    else
      flash[:notice] = t("static_pages.create.error")
      render :action => "new"
    end
  end

  def edit
    @static_page = StaticPage.find(params[:id])
  end

  def update
    @static_page = StaticPage.find(params[:id])
    if @static_page.update_attributes(params[:static_page])
      flash[:notice] = t("static_pages.update.success")
      redirect_to static_page_path(@static_page)
    else
      flash[:notice] = t("static_pages.update.error")
      render :action => "edit"
    end
  end

  def show
    @static_page = StaticPage.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    not_found
  end

  def destroy
    static_page = StaticPage.find(params[:id])
    if static_page.destroy
      flash[:notice] = t("static_pages.destroy.success")
      redirect_to static_pages_path
    else
      flash[:error] = t("static_pages.destroy.error")
      redirect_to static_page
    end
  end

  def index
    @static_pages = StaticPage.without_parent.order("work_as_directory, position").all
  end

  def attach_file
    if request.post?
      file = params[:file]
      if file.original_filename =~ /\.(jpeg|jpg|gif|png)$/i

        img_data = file.read
        if img_data.size <= Rails.application.config.static_pages.attachment_size_limit
          img_data_digest = Digest::MD5.new(img_data).hexdigest

          dest_filename = Rails.root.join("public", Rails.application.config.static_pages.attachment_path, img_data_digest + File.extname(file.original_filename))

          dest_dir = dest_filename.dirname
          dest_dir.mkdir if not dest_dir.exist?

          dest_filename.open("w") {|f| f.binmode; f.write img_data }

          #@alt_text = params[:alt_text]
          @public_filename =  "/" + dest_filename.to_s.split("/")[-2..-1].join("/")
          render :action => "attach_file_reply"
          return

        else # size validation
          @attachment_error = :too_big
        end

      else # suffix validation
        @attachment_error = :invalid_suffix
      end

    end

    render :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include CommonStaticPageHelpers
end

app/helpers/common_static_page_helpers.rb
module CommonStaticPageHelpers
  def link_to_static_page_version(version)
    static_page = StaticPage.version_of(version)
    if static_page
      link_to static_page.title, static_page_path(static_page)
    else
      "<!-- Not found version of #{h version} -->".html_safe
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def locales(&block)
    if @static_page and @static_page.version_of
      locales_iterator do |item|
        if alternative_page = StaticPage.find_by_version_of_id_and_locale(@static_page.version_of, item[:locale].to_s)
          item[:path_to_set] = set_locale_path(:locale => item[:locale], :return => static_page_path(alternative_page))
        end
        block.call item
      end
    else
      locales_iterator(&block)
    end
  end

  ValidTagsWithoutAttributes = %w(a ul ol li h2 h3 table thead tfoot tr th td caption)

  def sanitize_static_content(content)
    tokenizer = HTML::Tokenizer.new(content)
    output = ''
    ignore_last_anchor = true

    while token = tokenizer.next

      if token[0,1] != "<"
        output << escape_once(token)
        next
      end

      # Extract HTML tag and attributes
      html_tag = nil
      attributes = {}
      if token =~ /\A<(\/?\w+)(?:\s+(.*))?\s*>\Z/
        html_tag = $1
        if $2
          $2.scan(/(\w+)\s*=["'](.*?)["']/).each {|name, value| attributes[name] = value }
        end
      end

      next if html_tag.blank?

      case html_tag.downcase
      when "img"
        img_src = attributes["src"]
        if img_src =~ /\Ahttps?:\/\//i or img_src =~ %r|\A#{Regexp.escape(root_path + Rails.application.config.static_pages.attachment_path)}/|
          output << %[<img src="#{escape_once img_src}" alt="#{escape_once attributes["alt"].to_s}" />]
        end

      when "a"
        if attributes["href"].blank?
          ignore_last_anchor = true
        else
          ignore_last_anchor = false
          output << %[<a href="#{escape_once attributes["href"]}" rel="nofollow">]
        end

      when "/a"
        unless ignore_last_anchor
          output << "</a>"
        end

      when "br", "hr"
        output << "<#{html_tag} />"

      when "b", "strong"
        output << "<strong>"

      when "/b", "/strong"
        output << "</strong>"

      when "i", "em"
        output << "<em>"

      when "/i", "/em"
        output << "</em>"

      when "u"
        output << %[<span style="text-decoration: underline;">]

      when "div", "p"
        added_attr = ''
        if align = attributes["align"] and %w(right center left).include?(align)
          added_attr = " style=\"text-align: #{align}\""
        end
        output << "<p#{added_attr}>"

      when "/div", "/p"
        output << "</p>"

      when "s", "strike"
        output << %[<span style="text-decoration: line-through;">]

      when "/s", "/strike", "/u"
        output << %[</span>]

      else
        if ValidTagsWithoutAttributes.include?(html_tag.downcase.delete("/"))
          output << "<#{html_tag}>"
        end

      end

    end
    output.html_safe
  end

end

app/views/static_pages/_form.html.haml
%div.static-page
  = form_for @static_page, :html => {:id => "static_pages_form"} do |form|
    = error_messages_for @static_page
    %fieldset
      %legend
        = t("static_pages.form.title")
      %ul
        %li
          = form.label :title
          = form.text_field :title
        %li
          = form.label :content
          = form.text_area :content, :size => "60x25", :class => "wysiwyg-editor"

        %li
          = form.label :locale
          = form.select :locale, [[t("static_pages.form.fields.locale.any"), nil]] + I18n.available_locales.map {|l| [t("locale.label", :locale => l), l.to_s]}

        %li
          = form.label :position
          = form.text_field :position

        %li
          = form.label :version_of_id
          = form.select :version_of_id, [[t("static_pages.form.fields.version_of.none"), nil]] + StaticPage::Version.order("name").map {|v| [v.label, v.id] }
        %li
          = form.check_box :work_as_directory
          = form.label :work_as_directory
        %li
          = form.label :parent_id
          = form.select :parent_id, [[t("static_pages.form.fields.parent.none"), nil]] + StaticPage.without_parent.as_directory.reject{ |s| s.id == @static_page.id }.map{ |s| [s.title, s.id] }

    = buttons_bar do
      = button_ok
      = button_cancel(static_pages_path)

:javascript
  window.editor_insert_images_path = "#{escape_javascript static_page_attach_file_path}";

app/views/static_pages/_item.html.haml
%dl.static_page
  %dt
    = field_label(StaticPage, :title)
  %dd
    = link_to(item.title, static_page_path(item))
  %dt
    = field_label(StaticPage, :locale)
  %dd
    = item.locale
  - if item.work_as_directory
    %dt
      = t("static_pages.children.list")
    %dd
      = render :partial => "item", :collection => item.children

app/views/static_pages/attach_file.html.haml
!!! Strict
%html
  %head
    %title
      = t "static_pages.attachments.title"
    = stylesheet_link_tag "application.css"
    = javascript_include_tag "jquery.js"

  %body.wysiwyg_file_selector
    .dialog-box
      %p.caption
        = t("static_pages.attachments.message", :limit => number_to_human_size(Rails.application.config.static_pages.attachment_size_limit))

      - if @attachment_error
        %p.attachment-error
          = t "static_pages.attachments.errors.#@attachment_error"

      = form_tag controller.request.path, :multipart => true do
        .file-field
          %input{:type => "file", :name => "file"}

        .buttons
          = submit_tag t("static_pages.attachments.submit_button")
          = button_to_function t("buttons.cancel"), "parent.wysiwyg_insert_image_callback()"

    .uploading-message{:style => "display: none"}
      = t "static_pages.attachments.loading_msg"

:javascript
  $(function() {
    $(".dialog-box form input:submit").click(function() {
      $(".dialog-box").hide();
      $(".uploading-message").show();
    });
  });

app/views/static_pages/attach_file_reply.html.erb
<html>
  <head>
    <title>Reply</title>
  </head>
  <body>
  <script>
    parent.wysiwyg_insert_image_callback("<%= escape_javascript image_path(@public_filename) %>", "<%= escape_javascript @alt_text %>");
  </script>
  </body>
</html>"

app/views/static_pages/edit.html.haml
- content_for :page_title, @static_page.title

%h1
  = t("static_pages.edit.title")

= render :partial => "form"

app/views/static_pages/index.html.haml
- content_for :page_title, t("static_pages.page_title")

%h1
  = t("static_pages.title")

%div.static_pages
  = render :partial => "item", :collection => @static_pages

- content_for :secondary_bar do
  .box.manage_box
    %h2= t("static_pages.management.title")
    %ul
      %li= link_to t("static_pages.management.actions.new"), new_static_page_path

app/views/static_pages/new.html.haml
- content_for :page_title, t("static_pages.page_title")

%h1
  = t("static_pages.new.title")

= render :partial => "form"

app/views/static_pages/show.html.haml
- content_for :page_title, @static_page.title

%div.breadcrumbs
  - if parent = @static_page.parent
    %span
      = link_to(parent.title, static_page_path(parent))
      &nbsp;&gt;&nbsp;
  %span
    = @static_page.title

.static_pages
  %h1= @static_page.title
  = sanitize_static_content @static_page.content

- content_for :secondary_bar do
  - if current_user and current_user.admin?
    .box.manage_box
      %h2= t("static_pages.management.title")
      %ul
        %li= link_to t("static_pages.management.actions.index"), static_pages_path
        %li= link_to t("static_pages.management.actions.edit"), edit_static_page_path(@static_page)
        %li= link_to t("static_pages.management.actions.new"), new_static_page_path
        %li= link_to t("static_pages.management.actions.delete"), static_page_path(@static_page), :method => :delete, :confirm => t("static_pages.destroy.confirm")

  - parent = @static_page.parent ? @static_page.parent : @static_page
  - if parent.work_as_directory
    .box.section_box
      %h2= t("static_pages.children.title")
      .content
        .static_pages_children
          %ul
            - parent.children.each do |page|
              %li= link_to(page.title, static_page_path(page))